### ISSUE TITLE
Bug: BloodHoundDockerContainerCrash

### ISSUE THREAD

**Issue by tharindushakya** [SpecterOps/BloodHound#1011]
## Description:

After I have installed BHCE using docker as in the readme. when login into this first-time ask to reset password bloodhound it keeps stopping. there are 3 containers app-db-1, graph-db-1and blood hound. only bloodhound keep stopping. I have tried to rebuild the image, but same thing happens.

### Are you intending to fix this bug?

no

## Component(s) Affected:

- BHCE

## Steps to Reproduce:

1. Go to [specific page or endpoint]
2. Click on [button/element/etc.]
3. Enter [input/data]
4. See error at [this point]

## Expected Behavior:

reset the password and proceed.

## Actual Behavior:

*A description of what actually happened.*

## Screenshots/Code Snippets/Sample Files:

![image](https://github.com/user-attachments/assets/2feffd2d-5630-4bb7-8087-53c94d95df9f)

## Environment Information:

Docker (if using Docker): Current version: 4.33.1 (161083)

## Additional Information:

*Any additional context or information that might be helpful in understanding and diagnosing the issue.*

## Potential Solution (optional):

*If you have any ideas about what might be causing the issue or how it could be fixed, you can share them here.*

## Related Issues:

*If you've found related issues in the project's issue tracker, mention them here.*

## Contributor Checklist:

- [x] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [x] I have provided clear steps to reproduce the issue.
- [x] I have included relevant environment information details.
- [ ] I have attached necessary supporting documents.
- [x] I have checked that any JSON files I am attempting to upload to BloodHound are valid.

**Comment by StephenHinck** [comment]
Docker Error 137 occurs when your containers run out of memory. By default, Docker allocates minimal memory to containers, resulting in these issues.

Please make sure you have followed our minimum system specifications here: https://github.com/SpecterOps/BloodHound?tab=readme-ov-file#system-requirements
