### ISSUE TITLE
Feature: Disable Automatic Logout

### ISSUE THREAD

**Issue by cmprmsd** [SpecterOps/BloodHound#1014]
## Feature Description

When I work on security assessments and pause my virtual machine to call it a day, the next day I come back I see my BHCE tabs for one second after which the application notices the expired session and logs me out.

That way the last query is gone, which sometimes is an issue for me.

## Suggestion
There could be an option to disable automatic logout entirely or make it take some more time like a week of inactivity. Alternatively a redirect to the last query after logging in again would be also a valid solution.

**Comment by StephenHinck** [comment]
https://github.com/SpecterOps/BloodHound/issues/781 should include the query within your browser history. I'm going to close this ticket as we do not intend to remove the session expiration functionality at this time and the other feature request will handle the alternative option you requested.

**Comment by cmprmsd** [comment]
Fine for me 👍
