### ISSUE TITLE
Request for binaries

### ISSUE THREAD

**Issue by infosecconsultant** [SpecterOps/BloodHound#105]
**Feature Description:**

I appreciate that the majority of users might need/want bloodhound as a docker container, but I'd like to humbly request that you consider still providing pre-compiled binaries if at all possible. 

I often have to use client machines that don't have support for docker (usually due to age/old CPU's) or SOE's that have restrictions on what I can install on them. When I don't have authorisation to extract data from the environment to run on my own machines, this will have a significant impact in my workflow. 

If there's any questions, please let me know and I'll be happy to answer.
Thanks!

**Comment by pmehax0r** [comment]
+1 Also it is currently not possible to run docket in VMware pro unless VBS on host is disabled and majority of us use VMware pro instead of Hyper-V. 

Would really appreciate binaries that would allowed standalone running of BHCE on windows .

Thanks for your awesome work!
