### ISSUE TITLE
Upload failed with success message because of timeout

### ISSUE THREAD

**Issue by Kuermel** [SpecterOps/BloodHound#13]
If the upload fails due to 30s timeout it will still be shown as successful. 
The error message should be adjusted and a higher timeout should be set for the upload. 
![image](https://github.com/SpecterOps/BloodHound/assets/6574969/26819d4d-3583-4cd0-842a-07780e7eb9dd)

This happens e.g. with a slow network connection or large JSON files. 

Via API the timeout value can be increased to 60s, but not higher than the statically defined "maximumTimeout" value.
https://github.com/SpecterOps/BloodHound/blob/main/cmd/api/src/api/middleware/middleware.go#L101

**Comment by zinic** [comment]
There is a bit of technical debt in our request cancellation logic for eager timeouts that needs review. We'll track that effort and prioritization here once we get some internal discussion around it.

**Comment by zinic** [comment]
I've been kicking the tires with a custom client that just takes a really long time to upload and ran into no issues. The PR should effectively remove the limitation you're running into @Marshall-Hallenbeck.

**Comment by zinic** [comment]
This will roll into the next release of BloodHound CE - please feel free to reopen this issue if, after the release, you still experience this behavior.
