### ISSUE TITLE
Is bloodhound.py still compatible?

### ISSUE THREAD

**Issue by Phaedrik** [SpecterOps/BloodHound#15]
I am testing Bloodhound CE and using data collected from the python bloodhound ingestor. The data looks incomplete such as SIDs are not resolved or how domain users have only 3 members despite the domain having 1900 users.

I also apologize if this was the wrong place to ask this.

**Comment by zinic** [comment]
Using GitHub issues to ask feature support questions is just fine.

At this point in time, `bloodhound.py` is not supported with BloodHound CE. However, we are working on a new iteration of the generation script that's based on our own internal testing tooling. There is no available delivery timeline for it right now but I will reply to this issue once we have it in the pipeline.

**Comment by Phaedrik** [comment]
Thank you!

So I assume until the new generation script is created, if we cannot utilize Sharphound CE, its best to continue to use BH legacy?

**Comment by zinic** [comment]
First off, apologies, I misread that this was the Python ingestion client and immediately thought of the testing database generator.

My original reply however is still correct, we do not directly support `bloodhound.py`. Without an ETA for this I would suggest using the legacy version for now but expect further updates on this issue as we look into it!

**Comment by Cyb3rC3lt** [comment]
> Just a small update. We're going to reach out and work with the author of `bloodhound.py` when we have a moment to sync with them so that we can get it working with CE.

That's great, I did open an issue on Dirks repo but heard nothing yet. I might try to proxy my Windows machine through Kali into my clients domain tomorrow as a workaround for now. Hopefully SharpHound works okay using "runas netonly".

**Comment by Cyb3rC3lt** [comment]
@zinic Dirk confirms he is going to update his python ingestion tool 🎉

https://github.com/dirkjanm/BloodHound.py/issues/138

**Comment by StephenHinck** [comment]
I will close this issue with Dirk-jan's confirmation that he's updating `bloodhound.py`.
