### ISSUE TITLE
Vulnerable Babel/Traverse package in dev-dependancies

### ISSUE THREAD

**Issue by sectheops** [SpecterOps/BloodHound#174]
There seems to be an indirect usage of a vulnerable version of Babel/Traverse package (version: @babel/traverse@7.22.8) that can potentially lead to an arbitrary code execution during compilation.

The code is introduced through the following package chain:
bloodhound-ui@0.0.0 › bh-shared-ui@0.0.0-use.local › @vitejs/plugin-react@4.0.3 › @babel/core@7.22.9 › @babel/traverse@7.22.8 

Specifically, the explicit import of "vitejs/plugin-react@4.0.3" dependency in [this file](https://github.com/SpecterOps/BloodHound/blob/main/packages/javascript/bh-shared-ui/package.json) and is responsible for an indirect import of the compromised package "babel/traverse@7.22.8". 

**Source:**
[Link to the vulnerability documentation.](https://security.snyk.io/vuln/SNYK-JS-BABELTRAVERSE-5962462)

**Recommendation:**
Consider overriding the babel dependency to a patched version introduced through "@babel/traverse@7.23.2, @8.0.0-alpha.4".

The most upvoted answer in [this](https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions) post has a decent explanation on how to do so, in case it is needed.

**Comment by StephenHinck** [comment]
As an FYI, this is only pulled in as a dev dependency: https://github.com/SpecterOps/BloodHound/blob/9dd595987b8166403cca8d07b23bb6ee9fa036b4/cmd/ui/package.json#L80

**Comment by slokie-so** [comment]
Resolved as of Version 5.8.1
