### ISSUE TITLE
Add parameter to bulk request object properties in Domain Entity APIs

### ISSUE THREAD

**Issue by exploide** [SpecterOps/BloodHound#191]
**Feature Description:**

The "Domain Entity API" endpoints return lists of objects, e.g. of all computers (`/api/v2/domains/{object_id}/computers`) or all users (`/api/v2/domains/{object_id}/users`). These lists only contain the SID and the name of the object and nothing more. In order to get all properties of a single object, a further request to an endpoint like `/api/v2/users/{object_id}` is required.

When I'm interested in something like "give me all names and descriptions of all enabled user accounts", I need to send a request to `/api/v2/domains/{object_id}/users`, extract all SIDs and send additional requests for each and every account to `/api/v2/users/{object_id}` where the information I need is contained. This is very inefficient. Imagine a domain containing multiple thousands of user accounts. Getting the data out of it would require the same amount of HTTP requests to the API.

In old BloodHound, this was easy with a single Cypher query. Of course, the Neo4j database is still present, but as far as I understood, the new API is the preferred method to interact with BloodHound and eventually you might get rid of Neo4j. Correct me if I misperceived that.

To make this more efficient, I would like to propose a new optional parameter for the Domain Entity API endpoints, e.g. `allProperties=true`. If set, the endpoint responds not only with a list of SIDs and names but also with all the other properties. This would allow to bulk retrieve object properties. Using the already existing `skip` and `limit` parameters, it is possible to cope with situations where it is too much for one request/response.

**Current Behavior:**

Currently I need to request the properties of all objects individually which is inefficient.

**Desired Behavior:**

A possibility to bulk retrieve object properties would be more efficient.

**Use Case:**

A possible usecase are tools using BloodHound as their data source which offer additional functionality to view and edit data.

**Comment by StephenHinck** [comment]
@exploide using Cypher queries like you did in BloodHound Legacy would still work here. Something like:

```MATCH (n:User) WHERE n.domainsid = "{DOMAIN_SID}" RETURN n```

Let me know if there's something else you're still needing there and we can re-open!

**Comment by exploide** [comment]
Thanks for your reply. Of course, using Cypher queries against the Neo4j DB would work. At least when we expose the Neo4j port of the container.

The reason I opened this issue is because as far as I understood, the new API is the preferred method to interact with BloodHound and eventually you might get rid of Neo4j. There already is #253.

However, if the official recommendation is to just query Neo4j directly, I can live with that for now. Thank you!

**Comment by StephenHinck** [comment]
You are correct that Neo4J is on the path towards deprecation. When we released CE, Cypher support was built into the API. My recommendation is to query cypher against the API `/api/v2/graphs/cypher` :-)

**Comment by exploide** [comment]
Oh, I was not aware that Cypher is going to be used with Postgres as well. Nice to know. Thanks a lot! :)

**Comment by StephenHinck** [comment]
Yes, Cypher will remain the language of choice for interacting with the graph going forward (even with Postgres)!
