### ISSUE TITLE
User Role Mappings seem randomly identified

### ISSUE THREAD

**Issue by samwmarsh** [SpecterOps/BloodHound#198]
**Description:**

We're provisioning users through the API. We keep changing parts of our deployment, and as such, re-deploy to get a fresh slate. We've seen some odd behaviour where the role ID seems to be randomly assigned, we've seen the following:
*  Define the user common values
*  OLD       - 1 = Read Only # 2 = Upload Only # 3 = User        # 4 = Admin
* NEW       - 1 = Admin     # 2 = Read Only   # 3 = Upload Only # 4 = User
* NEW NEW   - 1 = User      # 2 = Admin       # 3 = Read Only   # 4 = Upload Only
* NEW NEW NEW - 1 = Admin      # 2 = Read Only # 3 = Upload Only   # 4 = User

This can also be seen in the UI with developer options, when changing the mapping of a user.

**Component(s) Affected:**

- [X] UI
- [X] API
- [ ] Neo4j
- [ ] PostgreSQL
- [ ] Data Collector (SharpHound, AzureHound)
- [ ] Other (tooling, documentation, etc.)

**Steps to Reproduce:**

1. Deploy BHE
2. Enable developer tools
3. Create user
4. Review network traffic for the Payload of the /api/v2/bloodhound-users/<id>
5. See the request payload, specifically the "roles" identifier [1], [2], [3], [4]
6. See error at this point

You may have to do multiple deployments to reproduce, we've noticed this change 4 times over the course of a week, however it doesn't seem to occur every deployment. 

**Expected Behavior:**

I'd expect identifiers to be hard-coded and therefore mappable so that automated provisioning tasks can apply a specific role to a user.

**Actual Behavior:**

The mapping ID seems to randomly change, causing provisioning scripts to have unexpected outcomes (like applying a user with a role id which was Read-Only, Administrator rights).

**Screenshots/Code Snippets/Sample Files:**

N/A

**Environment Information:**

Latest in main branch.

**Additional Information:**

*Any additional context or information that might be helpful in understanding and diagnosing the issue.*

**Potential Solution (Optional):**

We've found a current workaround of hitting /api/v2/roles and finding the 'Read-Only' reference, however I still feel like this is a bug/oversight and should be resolved:

```
def get_ro_role_id(session_token):

    roles_json = make_request('GET', '/api/v2/roles', session_token)
    roles = roles_json.json()['data']['roles']

    ro_role_id = [role['id'] for role in roles if role.get('name') == 'Read-Only']

    return ro_role_id[0]   
```

*If you have any ideas about what might be causing the issue or how it could be fixed, you can share them here.*

**Related Issues:**

*If you've found related issues in the project's issue tracker, mention them here.*

**Contributor Checklist:**

- [X] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [X] I have provided clear steps to reproduce the issue.
- [X] I have included relevant environment information details.
- [X] I have attached necessary supporting documents.
- [X] I have checked that any JSON files I am attempting to upload to BloodHound are valid.

**Comment by samwmarsh** [comment]
Using the python code provided, we've observed the following:

```
14:49:18.355 INFO    | Bloodhound-Provision | [+] Successfully gained session token for bloodhound
14:49:18.355 INFO    | Bloodhound-Provision | [+] Configured SAML Provider with ID: 1
14:49:18.355 INFO    | Bloodhound-Provision | [+] Read-Only ID: 1
```

```
16:31:32.203 INFO    | Bloodhound-Provision | [+] Successfully gained session token for bloodhound
16:31:32.203 INFO    | Bloodhound-Provision | [+] Configured SAML Provider with ID: 1
16:31:32.203 INFO    | Bloodhound-Provision | [+] Read-Only ID: 4
```

**Comment by superlinkx** [comment]
Converted this to an enhancement since things are working as engineering expects and as documented, but there's potentially room to discuss enhancements

**Comment by StephenHinck** [comment]
We appreciate the desire for this functionality but are unlikely to take it on from within our team.

**Comment by superlinkx** [comment]
Additional engineering note:

The API contract for these endpoints is defined with arbitrary integer ids. These aren't meant to be stable ids and are mostly used for backend housekeeping. They should be queried and mapped by an API client before adding the ids to other requests. If you run into other pain points after using the above solution, please feel free to open another ticket to discuss that pain and we can see what other options might be available.
