### ISSUE TITLE
Support Manual File Ingest Uploads > 1GB

### ISSUE THREAD

**Issue by rmcarden1** [SpecterOps/BloodHound#20]
For security professionals operating in large AD forests/domains, having the ability to upload large .json files generated by SharpHound would eliminate the need to parse and split the files, that could be several GBs, prior to uploading.

![image](https://github.com/SpecterOps/BloodHound/assets/98988480/6aee3abe-5e72-48c2-9948-cad7af1cb132)

**Comment by zinic** [comment]
We're tracking this internally and will post an update here once we have an implementation plan.

**Comment by Kuermel** [comment]
If you could upload zip files or zipped json files (json.gz) the 1 GB limit would no longer be a problem, even in large environments. 
See:
https://github.com/SpecterOps/BloodHound/issues/10

**Comment by aconite33** [comment]
After talking with @rvazarkar and @elikmiller in the Bloodhound slack channel, they guided me a way to submit large files via the API.

You can view the gist [here](https://gist.github.com/aconite33/37c23b24e71180750d0ab0c4679507fd).

I have tested this with a 15 GB from a real environment.

This should help folks with large files, especially with AzureHound generating output json files larger than 1GB.

Additionally, also tested this by trying to manually override the UI element (https://github.com/SpecterOps/BloodHound/blob/main/packages/javascript/bh-shared-ui/src/components/FileUploadDialog/FileUploadDialog.tsx#L23), however this resulted in a timeout as the upload took longer than 20 minutes.

Using the API, the upload took less than 60 seconds, and parsing the data took ~25 minutes.

**Comment by watson0x90** [comment]
Another approach would be to chunk the json file for uploading. 

- [https://github.com/bitsadmin/chophound/blob/main/chophound.py](https://github.com/bitsadmin/chophound/blob/main/chophound.py)

**Comment by StephenHinck** [comment]
This is resolved with v5.8.0
