### ISSUE TITLE
Ability to force log to contain username rather than guid OR pre-define admin user guid

### ISSUE THREAD

**Issue by samwmarsh** [SpecterOps/BloodHound#201]
**Feature Description:**

We are looking at logging with the attempt to create some alerts such as admin login. When reviewing this, we noticed that the username is only present once in the logs, and then the guid is present from there on. It would be helpful for our context to be able to either

- Pre-define a known guid
- Enable logging username for each log entry

**Current Behavior:**

At present, the username only appears once in the logs, and then the guid is present from there on.

**Desired Behavior:**

It would be helpful for our context to be able to either

- Pre-define a known guid
- Enable logging username for each log entry

**Use Case:**

Create alerts based on the logging for activities such as admin login/activity performed by admin user.

**Implementation Suggestions:**

- Pre-define a known guid
- Enable logging username for each log entry

**Additional Information:**

*Include any other relevant information that could help in understanding or implementing the feature.*

**Comment by StephenHinck** [comment]
This will be resolved in next week's release, v5.6.0.
