### ISSUE TITLE
database password other than default doesn't work

### ISSUE THREAD

**Issue by noraj** [SpecterOps/BloodHound#206]
**Description:**

database password other than default doesn't work

**Component(s) Affected:**

- [ ] UI
- [ ] API
- [ ] Neo4j
- [x] PostgreSQL
- [ ] Data Collector (SharpHound, AzureHound)
- [x] maybe the dockerization

**Steps to Reproduce:**

Clean env or `docker-compose down -v`

1. Take the example in https://github.com/SpecterOps/BloodHound/tree/main/examples/docker-compose
2. Edit .env `POSTGRES_PASSWORD` as well as the password in database.connection in `bloodhound.config.json`
3. docker-compose up
4. See error in the logs

```
bloodhound-docker-app-db-1      | 2023-11-10 09:50:30.404 UTC [91] FATAL:  password authentication failed for user "bloodhound"
bloodhound-docker-app-db-1      | 2023-11-10 09:50:30.404 UTC [91] DETAIL:  Password does not match for user "bloodhound".
bloodhound-docker-bloodhound-1  | {"level":"error","time":"2023-11-10T09:50:30.404653094Z","message":"failed to initialize database, got error failed to connect to `host=app-db user=bloodhound database=bloodhound`: server error (FATAL: password authentication failed for user \"bloodhound\" (SQLSTATE 28P01))"}
bloodhound-docker-app-db-1      |       Connection matched pg_hba.conf line 99: "host all all all md5"
bloodhound-docker-bloodhound-1  | {"level":"fatal","time":"2023-11-10T09:50:30.404668243Z","message":"Server start error: db connection error: error while attempting to create database connection: failed to connect to `host=app-db user=bloodhound database=bloodhound`: server error (FATAL: password authentication failed for user \"bloodhound\" (SQLSTATE 28P01))"}
bloodhound-docker-bloodhound-1 exited with code 1
```

**Expected Behavior:**

Being able to change default DB password

**Actual Behavior:**

Only the default password `bloodhoundcommunityedition` works.

**Screenshots/Code Snippets/Sample Files:**

![image](https://github.com/SpecterOps/BloodHound/assets/16578570/d626c030-25c1-4979-a920-a7c706615ad3)

**Environment Information:**

BloodHound: tag latest so it seems to be [5.1.0](https://hub.docker.com/layers/specterops/bloodhound/5.1.0/images/sha256-6a7c8d30d94d74aa5bab77cde3fd2b110750ebee3cd22fee26e9cea8105b5ff9?context=explore) by the way should disclose the BH version in the docker logs for easier debugging

Collector: not relevant

OS: ArchLinux

Docker (if using Docker): Docker version 24.0.7, build afdd53b4e3; Docker Compose version 2.23.0

**Additional Information:**

I used full alphanumeric password such as `MmCNXxKje9RiVMMQggRS` so it not an issue of escaping special characters.

**Potential Solution (Optional):**

This change doesn't resolve anything.

```diff
-POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-bloodhoundcommunityedition}
+POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
```

**Related Issues:**

N/A

**Contributor Checklist:**

- [ ] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [x] I have provided clear steps to reproduce the issue.
- [x] I have included relevant environment information details.
- [x] I have attached necessary supporting documents.
- [x] I have checked that any JSON files I am attempting to upload to BloodHound are valid.

**Comment by StephenHinck** [comment]
Hey there, this was resolved in https://github.com/SpecterOps/BloodHound/pull/306/checks, but we didn't realize we needed to tie the two together as it was fixed looking into a different issue. @superlinkx is going to pull through some docs updates to make it more clear how some of those environment variables are expected to work.

**Comment by superlinkx** [comment]
New documentation is available here: https://github.com/SpecterOps/BloodHound/wiki/Configuring-Database-Connections
