### ISSUE TITLE
Provide Demo JSON Files with a "bad" Active Directory for self-learning

### ISSUE THREAD

**Issue by abe-cyb87** [SpecterOps/BloodHound#238]
**Feature Description:**
DEMO JSON Files with "best of the worst" AD Configuration(s) to analyse, learn and demonstrate

*Provide a clear and concise description of the feature you're requesting.*
It would be nice to have demo JSON Files with a test Active Directory with lots of attack paths to explore. This would be nice to learn to analyze such paths and to demonstrate and teach others. 
They dont need to be updated often or anything like that. But if you want to get started with Bloodhound its nice to have some files at hand to learn about the gui.

**Current Behavior:**
There are no demo files :-)

*Explain how the software behaves currently in relation to the feature you're requesting.*

**Desired Behavior:**

*Describe how you envision the software behaving after the proposed feature is implemented.*

**Use Case:**
Analyze and Self-learn, Demonstration purpose and teaching co-workers.

*Explain the context in which this feature would be useful. How will it benefit users or contributors?*
To explore the bloodhound gui and learn about attack paths. Some paths you don't encounter often in the real world, but when you do its nice to have some practice with it. 

**Implementation Suggestions:**
Demo Active Directory with aaaaaaall the bad stuff in it and then let sharphound do its sniffing. 

*Optional: If you have any suggestions on how this feature could be implemented, you can provide them here.*

**Additional Information:**

*Include any other relevant information that could help in understanding or implementing the feature.*

**Comment by lbrauns** [comment]
Just to make you aware, you can easily build that for yourself :) The project BadBlood automates the build of a bad domain: https://github.com/davidprowe/BadBlood

**Comment by spyr0-sec** [comment]
There seems to be some demo files buried deep in the source code, someone from SpecterOps might be able to confirm if these are appropriate to use - https://github.com/SpecterOps/BloodHound/tree/main/cmd/api/src/test/fixtures/fixtures/v6/all
Otherwise to follow on from the above I've uploaded some that was generated from my lab (built on top of BadBlood) that also contains all ESC1-8 attack paths - https://github.com/spyr0-sec/AutomatedBadLab/tree/main/PostInstallationActivities/AutomatedBadLab/BHCE_Dataset

**Comment by StephenHinck** [comment]
Example data has been provided here: https://github.com/SpecterOps/BloodHound/tree/main/examples/sample-data
