### ISSUE TITLE
Import custom queries from Legacy Bloodhound

### ISSUE THREAD

**Issue by init5-SF** [SpecterOps/BloodHound#241]
Hi,

Sorry if that's a stupid question, but how can I import the content of `/.config/bloodhound/customqueries.json` (in legacy Bloodhound) into the new Bloodhound CE?

I've looked in the docs, but couldn't find any leads.

Thank you!

**Comment by StephenHinck** [comment]
You'd need to parse out the old json file, then use the API to import the queries into BHCE. Be aware of https://github.com/SpecterOps/BloodHound/issues/171 as that is currently blocking this capability, but it's on our radar to fix.

**Comment by init5-SF** [comment]
Hi @StephenHinck , thanks for the info
Is there gonna be any easier way to do this in the future?  like a file that could be manually edited or something?

**Comment by StephenHinck** [comment]
Saved queries are stored in the PostgreSQL database, not in a flat file like they used to be.

**Comment by init5-SF** [comment]
thank you for clarifying.
Is there gonna be any user friendly approach to do the import in the future? The API route doesn't look very easy, specially with the lack of examples because it's all still brand new
