### ISSUE TITLE
Enrichment failed

### ISSUE THREAD

**Issue by JonasBK** [SpecterOps/BloodHound#25]
_Issue created on the legacy repo by @janiskleinbergs_
https://github.com/BloodHoundAD/BloodHound/issues/689 

Hello,
I managed to collect the data using azurehound windows binary from my Azure AD, but upon .json file ingest through Bloodhound CE gui I get a status - failed - Enrichment failed.
Did I missed that I have to configure anything additionally?

web gui console says:
Object { stack: "Ge@[http://localhost:8080/ui/assets/index-b920366e.js:1277:85893\nwRe@http://localhost:8080/ui/assets/index-b920366e.js:1279:954\nf@http://localhost:8080/ui/assets/index-b920366e.js:1279:4111\n](http://localhost:8080/ui/assets/index-b920366e.js:1277:85893%5CnwRe@http://localhost:8080/ui/assets/index-b920366e.js:1279:954%5Cnf@http://localhost:8080/ui/assets/index-b920366e.js:1279:4111%5Cn)", message: "Request failed with status code 401", name: "AxiosError", code: "ERR_BAD_REQUEST", config: {…}, request: XMLHttpRequest, response: {…} }
​code: "ERR_BAD_REQUEST"
​config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​message: "Request failed with status code 401"
​name: "AxiosError"
​request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​response: Object { data: {…}, status: 401, statusText: "Unauthorized", … }
​stack: "Ge@[http://localhost:8080/ui/assets/index-b920366e.js:1277:85893\nwRe@http://localhost:8080/ui/assets/index-b920366e.js:1279:954\nf@http://localhost:8080/ui/assets/index-b920366e.js:1279:4111\n](http://localhost:8080/ui/assets/index-b920366e.js:1277:85893%5CnwRe@http://localhost:8080/ui/assets/index-b920366e.js:1279:954%5Cnf@http://localhost:8080/ui/assets/index-b920366e.js:1279:4111%5Cn)"
​: Object { constructor: Ge(e, t, n, r, i), toJSON: toJSON(), stack: "", … }
index-b920366e.js:269:24951
onError http://localhost:8080/ui/assets/index-b920366e.js:269
u http://localhost:8080/ui/assets/index-b920366e.js:269
d http://localhost:8080/ui/assets/index-b920366e.js:269

also Docker details panel upon ingest shows:
system32-bloodhound-1 | {"level":"error","time":"2023-08-14T08:22:05.139669565Z","message":"Analysis failed: Collected errors:\n\tError 0: error during azure post: property tenantid: property not found\n"}

**Comment by janiskleinbergs** [comment]
@zinic
Ok, I checked ingest files, they definitely have Tenant ID specified (replaced original upon submitting)
	"meta": {
		"count": 1,
		"type": "groups",
		"version": 4
	},
	"data": [
    {
        "DisplayName":  "Name",
        "OnPremisesSecurityIdentifier":  null,
        "ObjectID":  "xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx",
        "TenantID":  "xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx"

Seems there are no other errors, during ingestion also I get:
{"level":"error","time":"2023-08-15T11:10:41.937506692Z","message":"Node 2 is missing property tenantid"}

Not sure what it means and how to work around it?

**Comment by StephenHinck** [comment]
This issue will appear when the Azure tenant object is missing the tenantid field specifically. Validate that is present on the output from AzureHound and potentially re-import. We have released several versions of AzureHound since with collection improvements. Please feel free to re-open if this issue persists with any applicable logs from AzureHound.
