### ISSUE TITLE
Difference between this repo and https://github.com/BloodHoundAD/BloodHound?

### ISSUE THREAD

**Issue by CaledoniaProject** [SpecterOps/BloodHound#29]
I want to know why you created another repo? What's the difference between yours and the original one https://github.com/BloodHoundAD/BloodHound?

**Comment by Kuermel** [comment]
You can find a feature comparison on the following page: 
https://bloodhoundenterprise.io/bloodhound-feature-comparison/#:~:text=DATA%20COLLECTION-,BLOODHOUND%20LEGACY,-BLOODHOUND%20CE

**Comment by StephenHinck** [comment]
BloodHound CE is a complete rewrite of the original BloodHound project based on the BloodHound Enterprise codebase. Both BloodHound Legacy (hosted on the BloodHoundAD GitHub organization you linked to) and BloodHound CE are developed and maintained by SpecterOps. We've moved to a new repository during early access period and will migrate and archive the old repository once BloodHound CE reaches early access.
