### ISSUE TITLE
Bloodhound exit code 137 after inputting the password

### ISSUE THREAD

**Issue by aleemladha** [SpecterOps/BloodHound#37]
┌──(root㉿MANDIANT)-[/home/kali/bloodhound]
└─# curl -L https://github.com/SpecterOps/BloodHound/raw/main/examples/docker-compose/docker-compose.yml | docker-compose -f - up
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2555  100  2555    0     0   2953      0 --:--:-- --:--:-- --:--:-- 12839
Creating network "bloodhound_default" with the default driver
Creating volume "bloodhound_neo4j-data" with default driver
Creating volume "bloodhound_postgres-data" with default driver
Pulling app-db (docker.io/library/postgres:13.2)...
13.2: Pulling from library/postgres
69692152171a: Pull complete
a31b993d5cc6: Pull complete
f65921886500: Pull complete
b9c1a94e4ca8: Pull complete
435dd99ceb68: Pull complete
d3ee8e88c67c: Pull complete
84b08674f942: Pull complete
7d358e850d3e: Pull complete
adf2c63307b4: Pull complete
27ff0e95dd24: Pull complete
550e7b1ab95a: Pull complete
2287baf15bf8: Pull complete
97d11a196325: Pull complete
0f11fc82fe79: Pull complete
Digest: sha256:0eee5caa50478ef50b89062903a5b901eb818dfd577d2be6800a4735af75e53f
Status: Downloaded newer image for postgres:13.2
Pulling graph-db (docker.io/library/neo4j:4.4)...
4.4: Pulling from library/neo4j
1d5252f66ea9: Pull complete
906a67c0c0e1: Pull complete
e1edb1e1a590: Pull complete
f86c3c2aca7f: Pull complete
664d63dc50e7: Pull complete
Digest: sha256:cc79ca7c9c4d7d5271466ed69b562d405147efb032e4d53dd17abbbd5a0dbae5
Status: Downloaded newer image for neo4j:4.4
Pulling bloodhound (docker.io/specterops/bloodhound:latest)...
latest: Pulling from specterops/bloodhound
a7ca0d9ba68f: Pull complete
fe5ca62666f0: Pull complete
b02a7525f878: Pull complete
fcb6f6d2c998: Pull complete
e8c73c638ae9: Pull complete
1e3d9b7d1452: Pull complete
4aa0ea1413d3: Pull complete
7c881f9ab25e: Pull complete
5627a970d25e: Pull complete
c10765aee595: Pull complete
5aa615974fb7: Pull complete
4f4fb700ef54: Pull complete
de43e2930f60: Pull complete
fe5375d43e30: Pull complete
fe7155412cc9: Pull complete
9cf2ab74ce31: Pull complete
Digest: sha256:c5947a0a70d14efde933c09767e61245c5910cb3571957b1d6c2be21d5efaf2a
Status: Downloaded newer image for specterops/bloodhound:latest
Creating bloodhound_app-db_1   ... done
Creating bloodhound_graph-db_1 ... done
Creating bloodhound_bloodhound_1 ... done
Attaching to bloodhound_graph-db_1, bloodhound_app-db_1, bloodhound_bloodhound_1
app-db_1      | The files belonging to this database system will be owned by user "postgres".
app-db_1      | This user must also own the server process.
app-db_1      | 
app-db_1      | The database cluster will be initialized with locale "en_US.utf8".
app-db_1      | The default database encoding has accordingly been set to "UTF8".
app-db_1      | The default text search configuration will be set to "english".
app-db_1      | 
app-db_1      | Data page checksums are disabled.
app-db_1      | 
app-db_1      | fixing permissions on existing directory /var/lib/postgresql/data ... ok
app-db_1      | creating subdirectories ... ok
graph-db_1    | Changed password for user 'neo4j'. IMPORTANT: this change will only take effect if performed before the database is started for the first time.
app-db_1      | selecting dynamic shared memory implementation ... posix
app-db_1      | selecting default max_connections ... 100
app-db_1      | selecting default shared_buffers ... 128MB
graph-db_1    | 2023-08-16 07:17:45.754+0000 INFO  Starting...
graph-db_1    | 2023-08-16 07:17:46.196+0000 INFO  This instance is ServerId{c6f39217} (c6f39217-cb60-44ff-a611-4ebe8b5a6de8)
graph-db_1    | 2023-08-16 07:17:47.545+0000 INFO  ======== Neo4j 4.4.24 ========
app-db_1      | selecting default time zone ... Etc/UTC
app-db_1      | creating configuration files ... ok
graph-db_1    | 2023-08-16 07:17:49.332+0000 INFO  Initializing system graph model for component 'security-users' with version -1 and status UNINITIALIZED
graph-db_1    | 2023-08-16 07:17:49.342+0000 INFO  Setting up initial user from `auth.ini` file: neo4j
app-db_1      | running bootstrap script ... ok
graph-db_1    | 2023-08-16 07:17:49.342+0000 INFO  Creating new user 'neo4j' (passwordChangeRequired=false, suspended=false)
graph-db_1    | 2023-08-16 07:17:49.352+0000 INFO  Setting version for 'security-users' to 3
graph-db_1    | 2023-08-16 07:17:49.355+0000 INFO  After initialization of system graph model component 'security-users' have version 3 and status CURRENT
graph-db_1    | 2023-08-16 07:17:49.359+0000 INFO  Performing postInitialization step for component 'security-users' with version 3 and status CURRENT
graph-db_1    | 2023-08-16 07:17:49.668+0000 INFO  Bolt enabled on 0.0.0.0:7687.
graph-db_1    | 2023-08-16 07:17:50.624+0000 INFO  Remote interface available at http://localhost:7474/
graph-db_1    | 2023-08-16 07:17:50.629+0000 INFO  id: 856E8A67480BA632CA54C7170F83FFC45624D74220DA88BF3FB845D8CC485701
graph-db_1    | 2023-08-16 07:17:50.629+0000 INFO  name: system
graph-db_1    | 2023-08-16 07:17:50.629+0000 INFO  creationDate: 2023-08-16T07:17:48.184Z
graph-db_1    | 2023-08-16 07:17:50.630+0000 INFO  Started.
app-db_1      | performing post-bootstrap initialization ... ok
app-db_1      | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
app-db_1      | You can change this by editing pg_hba.conf or using the option -A, or
app-db_1      | --auth-local and --auth-host, the next time you run initdb.
app-db_1      | ok
app-db_1      | 
app-db_1      | 
app-db_1      | Success. You can now start the database server using:
app-db_1      | 
app-db_1      |     pg_ctl -D /var/lib/postgresql/data -l logfile start
app-db_1      | 
app-db_1      | waiting for server to start....2023-08-16 07:17:40.510 UTC [48] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
app-db_1      | 2023-08-16 07:17:40.512 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
app-db_1      | 2023-08-16 07:17:40.520 UTC [49] LOG:  database system was shut down at 2023-08-16 07:17:40 UTC
app-db_1      | 2023-08-16 07:17:40.526 UTC [48] LOG:  database system is ready to accept connections
app-db_1      |  done
app-db_1      | server started
app-db_1      | CREATE DATABASE
app-db_1      | 
app-db_1      | 
app-db_1      | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
app-db_1      | 
app-db_1      | waiting for server to shut down...2023-08-16 07:17:40.807 UTC [48] LOG:  received fast shutdown request
app-db_1      | .2023-08-16 07:17:40.809 UTC [48] LOG:  aborting any active transactions
app-db_1      | 2023-08-16 07:17:40.810 UTC [48] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
app-db_1      | 2023-08-16 07:17:40.812 UTC [50] LOG:  shutting down
app-db_1      | 2023-08-16 07:17:40.824 UTC [48] LOG:  database system is shut down
app-db_1      |  done
app-db_1      | server stopped
app-db_1      | 
app-db_1      | PostgreSQL init process complete; ready for start up.
app-db_1      | 
app-db_1      | 2023-08-16 07:17:40.930 UTC [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
app-db_1      | 2023-08-16 07:17:40.930 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
app-db_1      | 2023-08-16 07:17:40.930 UTC [1] LOG:  listening on IPv6 address "::", port 5432
app-db_1      | 2023-08-16 07:17:40.933 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
app-db_1      | 2023-08-16 07:17:40.940 UTC [76] LOG:  database system was shut down at 2023-08-16 07:17:40 UTC
app-db_1      | 2023-08-16 07:17:40.970 UTC [1] LOG:  database system is ready to accept connections
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.249848874Z","message":"Reading configuration found at /bloodhound.config.json"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.250861911Z","message":"Logging configured"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.728263671Z","message":"This is a new database. Creating a migration entry for version v5.0.0"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.737505144Z","message":"Permission permission://graphdb/Write created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.738110766Z","message":"Permission permission://graphdb/Read created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.73854222Z","message":"Permission permission://app/ReadAppConfig created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.739225801Z","message":"Permission permission://app/WriteAppConfig created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.739627266Z","message":"Permission permission://collection/ManageJobs created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.740147049Z","message":"Permission permission://clients/Manage created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.740546913Z","message":"Permission permission://clients/Tasking created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.740929086Z","message":"Permission permission://auth/CreateToken created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.741686354Z","message":"Permission permission://auth/ManageUsers created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.742052102Z","message":"Permission permission://auth/ManageProviders created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.742360235Z","message":"Permission permission://auth/ManageSelf created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.742643329Z","message":"Permission permission://auth/ManageAppConfig created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.742907604Z","message":"Permission permission://risks/GenerateReport created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.743213445Z","message":"Permission permission://risks/ManageRisks created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.748954538Z","message":"Role Administrator created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.751698045Z","message":"Role Read-Only created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.753306852Z","message":"Role Upload-Only created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.754708677Z","message":"Role User created during migration"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.756767972Z","message":"Missing the default Admin Tier Zero asset group. Creating it now."}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.76090028Z","message":"Configuration parameter auth.password_expiration_window created"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.762035152Z","message":"Configuration parameter neo4j.configuration created"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.764586174Z","message":"Feature flag entity_panel_cache created"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.765425255Z","message":"Feature flag butterfly_analysis created"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.766625173Z","message":"Feature flag enable_saml_sso created"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.767864973Z","message":"Feature flag scope_collection_by_ou created"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.768658285Z","message":"Feature flag azure_support created"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:53.769759528Z","message":"Feature flag reconciliation created"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:57.22773999Z","message":"###################################################################"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:57.228308691Z","message":"#                                                                 #"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:57.228314823Z","message":"# Initial Password Set To:    SnLRS7jc57lt4ND5wYmpAnZRAV89cczs    #"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:57.228316656Z","message":"#                                                                 #"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:17:57.228317838Z","message":"###################################################################"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:18:09.963293221Z","message":"This is a new graph database. Creating a migration entry for GraphDB version v5.0.0"}
bloodhound_1  | {"level":"error","time":"2023-08-16T07:18:10.284322267Z","message":"invalid neo4j configuration supplied; returning default values"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:18:10.28435549Z","message":"Starting daemon API Daemon"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:18:10.284881432Z","message":"Starting daemon Tools API"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:18:10.284915556Z","message":"Starting daemon Data Pruning Daemon"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:18:10.284920866Z","message":"Starting daemon Data Pipe Daemon"}
bloodhound_1  | {"level":"info","time":"2023-08-16T07:18:10.28494399Z","message":"Server started successfully"}
bloodhound_1  | {"level":"info","remote_addr":"172.21.0.1:58922","proto":"HTTP/1.1","referer":"http://localhost:8080/ui/login","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","request_id":"227ce4fb-cecc-436b-9b96-f491d3766412","request_bytes":0,"response_bytes":25,"status":200,"elapsed":30.56528,"time":"2023-08-16T07:19:15.994897108Z","message":"GET /api/v2/saml/sso"}
bloodhound_1  | {"level":"info","remote_addr":"172.21.0.1:39836","proto":"HTTP/1.1","referer":"http://localhost:8080/ui/login","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","request_id":"6aaf2b5b-f5c5-4b41-b061-4b912ca0cd97","request_bytes":0,"response_bytes":25,"status":200,"elapsed":16.647286,"time":"2023-08-16T07:19:22.223334083Z","message":"GET /api/v2/saml/sso"}
bloodhound_1  | {"level":"info","remote_addr":"172.21.0.1:58922","proto":"HTTP/1.1","referer":"","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","request_id":"58340dbf-9451-453d-bffd-eb66bf33125d","request_bytes":0,"response_bytes":1225,"status":200,"elapsed":27.375077,"time":"2023-08-16T07:19:22.23069912Z","message":"GET /ui"}
bloodhound_1  | {"level":"info","remote_addr":"172.21.0.1:58922","proto":"HTTP/1.1","referer":"http://localhost:8080/ui","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","request_id":"e2aae7bf-ab70-49c3-82c5-210548bc9c2a","request_bytes":0,"response_bytes":1107270,"status":200,"elapsed":8.710849,"time":"2023-08-16T07:19:22.381043466Z","message":"GET /ui/assets/index-b920366e.js"}
bloodhound_1  | {"level":"info","remote_addr":"172.21.0.1:58922","proto":"HTTP/1.1","referer":"http://localhost:8080/ui","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","request_id":"ebecebe5-bca8-4c46-b86d-1e9eeb053cd0","request_bytes":0,"response_bytes":31612,"status":200,"elapsed":1.052605,"time":"2023-08-16T07:19:22.390618846Z","message":"GET /ui/assets/index-c7b10b6b.css"}
bloodhound_1  | {"level":"info","remote_addr":"172.21.0.1:58922","proto":"HTTP/1.1","referer":"http://localhost:8080/ui","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","request_id":"a85f18fa-53c0-4591-833f-0fd2df62a88a","request_bytes":0,"response_bytes":4286,"status":200,"elapsed":1.081759,"time":"2023-08-16T07:19:22.616141365Z","message":"GET /ui/favicon.ico"}
bloodhound_1  | {"level":"info","remote_addr":"172.21.0.1:58922","proto":"HTTP/1.1","referer":"http://localhost:8080/ui","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","request_id":"b5dc0b60-bf09-4a63-9df0-a4c2a2de0fa8","request_bytes":0,"response_bytes":2081,"status":200,"elapsed":35.680396,"time":"2023-08-16T07:19:22.668897909Z","message":"GET /api/v2/features"}
bloodhound_1  | {"level":"info","remote_addr":"172.21.0.1:39842","proto":"HTTP/1.1","referer":"http://localhost:8080/ui/login","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","request_id":"0387f8b5-422d-4d3b-86ec-b36c5e565c48","request_bytes":0,"response_bytes":4260,"status":200,"elapsed":0.455218,"time":"2023-08-16T07:19:22.68904097Z","message":"GET /ui/assets/Login-ef659d8a.js"}
bloodhound_1  | {"level":"info","remote_addr":"172.21.0.1:58922","proto":"HTTP/1.1","referer":"http://localhost:8080/ui/assets/index-b920366e.js","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","request_id":"2350c171-4b49-40cb-8086-9b275129d49e","request_bytes":0,"response_bytes":4260,"status":200,"elapsed":0.232609,"time":"2023-08-16T07:19:22.690231716Z","message":"GET /ui/assets/Login-ef659d8a.js"}
bloodhound_1  | {"level":"info","remote_addr":"172.21.0.1:39854","proto":"HTTP/1.1","referer":"http://localhost:8080/ui/login","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","request_id":"539fbc0d-1e66-416e-909d-9765ea19d0ac","request_bytes":0,"response_bytes":443,"status":200,"elapsed":0.98582,"time":"2023-08-16T07:19:22.690832669Z","message":"GET /ui/assets/LoginPage-30eeb27b.js"}
bloodhound_1  | {"level":"info","remote_addr":"172.21.0.1:58922","proto":"HTTP/1.1","referer":"http://localhost:8080/ui/assets/Login-ef659d8a.js","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","request_id":"9fb9c74c-1325-4592-8353-1b873fb89292","request_bytes":0,"response_bytes":443,"status":200,"elapsed":0.224884,"time":"2023-08-16T07:19:22.720451122Z","message":"GET /ui/assets/LoginPage-30eeb27b.js"}
bloodhound_1  | {"level":"info","remote_addr":"172.21.0.1:58922","proto":"HTTP/1.1","referer":"http://localhost:8080/ui/login","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","request_id":"aab33311-0b4d-4f39-80d1-acf6a9cb809b","request_bytes":0,"response_bytes":27197,"status":200,"elapsed":1.167364,"time":"2023-08-16T07:19:22.740378547Z","message":"GET /ui/img/logo-transparent-full.svg"}
bloodhound_1  | {"level":"info","remote_addr":"172.21.0.1:58922","proto":"HTTP/1.1","referer":"http://localhost:8080/ui/login","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","request_id":"32a28d99-20c7-4e68-a891-d942bfe4e2cd","request_bytes":0,"response_bytes":25,"status":200,"elapsed":2.294147,"time":"2023-08-16T07:19:22.77462122Z","message":"GET /api/v2/saml/sso"}
bloodhound_bloodhound_1 exited with code 137

**Comment by superlinkx** [comment]
Code 137 means the container was killed due to memory limits being reached. Can you provide the amount of RAM you had available while running this?

**Comment by StephenHinck** [comment]
Since Code 137 indicates lack of resources granted to the container, I'm going to close out this issue. If you're still experiencing issues or have additional questions, please feel free to respond and re-open.

**Comment by adityatelange** [comment]
> Code 137 means the container was killed due to memory limits being reached. Can you provide the amount of RAM you had available while running this?

For me, its on kali with 4Gigs RAM. Crashes wile I try to reset the password.

**Comment by adityatelange** [comment]
Once it crashes I don't get the initial password again, making me delete the volumes and restart the process. IMHO I hate the UX.
