### ISSUE TITLE
can't open bloodhound 

### ISSUE THREAD

**Issue by mohamedeletrepy** [SpecterOps/BloodHound#43]
how to solve that 👍 
┌─[mavric@parrot]─[/opt/bloodhound]
└──╼ $docker-compose up
Attaching to bloodhound-app-db-1, bloodhound-bloodhound-1, bloodhound-graph-db-1
Error response from daemon: OCI runtime create failed: container with id exists: 568d1919ae5ffd9eb6028f8c76a3eb5c1ed2ab35cf6113e51f25e0cb456dc305: unknown

**Comment by StephenHinck** [comment]
Try running:

- docker compose down --rmi all -v
- docker compose up

That error indicates that a container is in a bad state. The first command above will drop the existing volumes and containers, and re-pull all of the above from the container registry before starting up.

Going to close out this issue, but please feel free to respond and re-open if that does not resolve it.
