### ISSUE TITLE
Support RELATIONSHIPS and TYPE verbs in Cypher

### ISSUE THREAD

**Issue by cmprmsd** [SpecterOps/BloodHound#489]
**Description:**
It seems filtering by edge type is not possible in the new UI. I can use the query below to filter for all edges but X. That way my queries stay valid even when there are new edges in future versions of Bloodhound.

**Component(s) Affected:**

- [x] UI
- [x] API
- [x] Neo4j
- [ ] PostgreSQL
- [ ] Data Collector (SharpHound, AzureHound)
- [ ] Other (tooling, documentation, etc.)

**Steps to Reproduce:**

1. Go to Cypher
2. Enter 
```cypher
MATCH p=allshortestPaths((n)-[*1..]->(g:Group)) WHERE g.objectid ENDS WITH "-512" AND n<>g AND NONE(rel in relationships(p) WHERE type(rel)="LocalToComputer")  RETURN p
```
4. See error at bottom and in console
```
{ message: `line 1:100 no viable alternative at input 'MATCH p=allshortestPaths((n)-[*1..]->(g:Group)) WHERE g.objectid ENDS WITH "-512" AND n<>g AND NONE(rel'`, context: "" }
```

**Expected Behavior:**
The query should just exclude LocalToComputer edges.

**Actual Behavior:**

The query will not execute in BHCE. It does work for the old app and the neo4j console. 

![image](https://github.com/SpecterOps/BloodHound/assets/73472903/5a63e989-5daa-48bb-a81b-446703494648)

**Environment Information:**

BloodHound: there is no version tag in the BHCE UI. Docker tag is latest.

Collector: SharpHound

**Contributor Checklist:**
- [x] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [x] I have provided clear steps to reproduce the issue.
- [x] I have included relevant environment information details.
- [x] I have attached necessary supporting documents.
- [x] I have checked that any JSON files I am attempting to upload to BloodHound are valid.

**Comment by slokie-so** [comment]
Hello, 
Following a review of the request,  BloodHound, by default, supports the Open Cypher spec with some limitations.   The Neo4J implementation that is referenced in this query is not currently supported.   Please adjust your query accordingly to the Open Cypher spec.
