### ISSUE TITLE
Empty Compose File

### ISSUE THREAD

**Issue by Cy-Beard** [SpecterOps/BloodHound#520]
**Description:**
Unable to compose.
curl -L https://ghst.ly/getbhce -o docker-compose.yml | docker compose -f - up
and i get the following error:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   190  100   190    0     0    267      0 --:--:-- --:--:-- --:--:--   270
100  3618  100  3618    0     0   3895      0 --:--:-- --:--:-- --:--:--  3895
empty compose file
![image](https://github.com/SpecterOps/BloodHound/assets/41340083/505d5ec6-8add-4011-9ff5-8ce54a4a1df1)

*A clear and concise description of the bug you're encountering.*

**Component(s) Affected:**

- [ ] UI
- [ ] API
- [ ] Neo4j
- [ ] PostgreSQL
- [ ] Data Collector (SharpHound, AzureHound)
- [ ] Other (tooling, documentation, etc.)

**Steps to Reproduce:**

1. Go to [specific page or endpoint] : curl -L https://ghst.ly/getbhce -o docker-compose.yml | docker compose -f - up
2. Click on [button/element/etc.]
3. Enter [input/data]
4. See error at [this point]

**Expected Behavior:**

*A description of what you expected to happen.*
docker compose to build the docker image.

**Actual Behavior:**
empty compose file

*A description of what actually happened.*
Empty compose file, unable to build the container within windows 10.

**Screenshots/Code Snippets/Sample Files:**
![image](https://github.com/SpecterOps/BloodHound/assets/41340083/df151978-ccb1-4965-ae84-e16da1c4f5d4)

*If applicable, add screenshots, relevant code snippets, or sample files that help illustrate the issue.*

**Environment Information:**
Windows 10 OS

BloodHound: [BloodHound version or revision]
Bloodhound CE

Collector: [SharpHound version / AzureHound version]

OS: [your OS and version]
Windows 10 Version 22H2

Browser (if UI related): [browser name and version]

Node.js (if UI related: [Node.js version]

Go (if API related): [Go version]

Database (if persistence related): [Neo4j version / PostgreSQL version]

Docker (if using Docker): [docker version]

**Additional Information:**

*Any additional context or information that might be helpful in understanding and diagnosing the issue.*

**Potential Solution (Optional):**

*If you have any ideas about what might be causing the issue or how it could be fixed, you can share them here.*

**Related Issues:**

*If you've found related issues in the project's issue tracker, mention them here.*

**Contributor Checklist:**

- [ ] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [ ] I have provided clear steps to reproduce the issue.
- [ ] I have included relevant environment information details.
- [ ] I have attached necessary supporting documents.
- [ ] I have checked that any JSON files I am attempting to upload to BloodHound are valid.

**Comment by lap1nou** [comment]
Hello @Cy-Beard,

You are not using the command correctly, use this one:
```bash
curl -L https://ghst.ly/getbhce | docker compose -f - up
```

The reason yours is not working is because you are outputting the content in the `docker-compose.yml` file and then you are asking `docker compose` to read the content from stdin but stdin was written to the file so it's empty, if you want to use a file instead use:
```bash
curl -L https://ghst.ly/getbhce -o docker-compose | docker compose up
```

Regards.

**Comment by StephenHinck** [comment]
@Cy-Beard The issue appears to be an issue with how Docker is running; searching for the error message identifies several options:

- https://github.com/docker/for-win/issues/12548
- https://stackoverflow.com/questions/40459280/docker-cannot-start-on-windows
- https://stackoverflow.com/questions/67160140/docker-error-during-connect-in-the-default-daemon-configuration-on-windows-th

**Comment by Cy-Beard** [comment]
After some searching into, I found that Windows cannot run Docker-cli on its own even though it can be installed via chocolatey. Its still needs to have WSL2 installed and running in order to run docker-cli. If not, then I would need to installed docker desktop which is not an approved app yet for the business. Guess I cannot go down this route. 
Thank you for your help.
