### ISSUE TITLE
No password displayed

### ISSUE THREAD

**Issue by Autumn-27** [SpecterOps/BloodHound#537]
be1681d2fb7c: Pull complete
b6824ed73363: Pull complete
7c12895b777b: Pull complete
33e068de2649: Pull complete
5664b15f108b: Pull complete
27be814a09eb: Pull complete
4aa0ea1413d3: Pull complete
9ef7d74bdfdf: Pull complete
9112d77ee5b1: Pull complete
f4f09da9e5d2: Pull complete
f0b47f429d37: Pull complete
4f4fb700ef54: Pull complete
80c6462b9cc3: Pull complete
c0b5ef029f4f: Pull complete
9154b99ae9d1: Pull complete
17feac8169dd: Pull complete
Digest: sha256:41eb63fe93f4e36cf5d2c2c28f66c2ca19191a4925a817ecf633fe4b041ef667
Status: Downloaded newer image for specterops/bloodhound:latest
Creating bloodhound_app-db_1   ... done
Creating bloodhound_graph-db_1 ... done
Creating bloodhound_bloodhound_1 ... done
Attaching to bloodhound_app-db_1, bloodhound_graph-db_1, bloodhound_bloodhound_1
app-db_1      | 
app-db_1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
app-db_1      | 
app-db_1      | 2024-04-04 08:55:57.280 UTC [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on 
graph-db_1    | Changed password for user 'neo4j'. IMPORTANT: this change will only take effect if performed
app-db_1      | 2024-04-04 08:55:57.281 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
app-db_1      | 2024-04-04 08:55:57.281 UTC [1] LOG:  listening on IPv6 address "::", port 5432
graph-db_1    | 2024-04-04 08:56:00.056+0000 INFO  Starting...
app-db_1      | 2024-04-04 08:55:57.286 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL
app-db_1      | 2024-04-04 08:55:57.289 UTC [27] LOG:  database system was shut down at 2024-04-04 08:34:03 
app-db_1      | 2024-04-04 08:55:57.293 UTC [1] LOG:  database system is ready to accept connections
graph-db_1    | 2024-04-04 08:56:00.252+0000 INFO  This instance is ServerId{001a4f34} (001a4f34-7bb3-4584-9
graph-db_1    | 2024-04-04 08:56:00.832+0000 INFO  ======== Neo4j 4.4.32 ========
graph-db_1    | 2024-04-04 08:56:01.330+0000 INFO  Performing postInitialization step for component 'securit
graph-db_1    | 2024-04-04 08:56:01.330+0000 INFO  Updating the initial password in component 'security-user
graph-db_1    | 2024-04-04 08:56:04.045+0000 INFO  Bolt enabled on 0.0.0.0:7687.
graph-db_1    | 2024-04-04 08:56:04.403+0000 INFO  Remote interface available at http://localhost:7474/
graph-db_1    | 2024-04-04 08:56:04.405+0000 INFO  id: A2B8C044A9E442D7CD06D484B333CCB8AF54CF2557E736725C8C6
graph-db_1    | 2024-04-04 08:56:04.405+0000 INFO  name: system
graph-db_1    | 2024-04-04 08:56:04.405+0000 INFO  creationDate: 2024-04-04T06:41:43.646Z
graph-db_1    | 2024-04-04 08:56:04.406+0000 INFO  Started.
bloodhound_1  | {"level":"info","time":"2024-04-04T08:56:07.684016718Z","message":"Reading configuration fou
bloodhound_1  | {"level":"info","time":"2024-04-04T08:56:07.684493822Z","message":"Logging configured"}
bloodhound_1  | {"level":"info","time":"2024-04-04T08:56:07.701852635Z","message":"No database driver has be
bloodhound_1  | {"level":"info","time":"2024-04-04T08:56:07.701906416Z","message":"Connecting to graph using
bloodhound_1  | {"level":"info","time":"2024-04-04T08:56:07.710494748Z","message":"No new SQL migrations to 
bloodhound_1  | {"level":"error","time":"2024-04-04T08:56:08.593886673Z","message":"invalid neo4j configurat
bloodhound_1  | {"level":"info","time":"2024-04-04T08:56:08.594011958Z","message":"Starting daemon API Daemo
bloodhound_1  | {"level":"info","time":"2024-04-04T08:56:08.594018901Z","message":"Starting daemon Tools API
bloodhound_1  | {"level":"info","time":"2024-04-04T08:56:08.594020484Z","message":"Starting daemon Data Prun
bloodhound_1  | {"level":"info","time":"2024-04-04T08:56:08.594022337Z","message":"Starting daemon Data Pipe
bloodhound_1  | {"level":"info","time":"2024-04-04T08:56:08.59402363Z","message":"Server started successfull

**Comment by StephenHinck** [comment]
@Autumn-27 - looks like you're re-using a previous deployment:

> PostgreSQL Database directory appears to contain a database; Skipping initialization

That means your old password will still work. If you're not sure what it is any longer, you can reset your environment with: `docker compose down -v`
