### ISSUE TITLE
upload crashes

### ISSUE THREAD

**Issue by osodg** [SpecterOps/BloodHound#568]
When I click the upload button the app closes without warning.

**Comment by StephenHinck** [comment]
Can you please provide additional information to help us troubleshoot? Some helpful items would include:

- What version of BloodHound?
- What version of Docker?
- What Browser (including version) are you using?
- Can you record your screen as it happens?

**Comment by slokie-so** [comment]
None of the requested information was provided,  if you're continuing to have this issue,  please reopen with the additional information provided
