### ISSUE TITLE
Pre-built searches not showing up

### ISSUE THREAD

**Issue by Khatcode** [SpecterOps/BloodHound#579]
**Description:**

Pre-built queries don't seem to be showing up in my version of Docker Bloodhound CE. I am using the most current version of both bloodhound ce and docker. I see in a lot of guides that everyone else seems to have it. Am I doing something wrong? I've installed it all correctly. Also, Is there another way of saving custom queries without using the API? Can I modify the postgresql database and just add them there?

Any help would be appreciated. Thanks 

![image](https://github.com/SpecterOps/BloodHound/assets/68708968/736190e0-2383-4c94-8df5-c5cf82a573e5)

**Component(s) Affected:**

- [ X] UI
- [ ] API
- [ ] Neo4j
- [ ] PostgreSQL
- [ ] Data Collector (SharpHound, AzureHound)
- [ ] Other (tooling, documentation, etc.)

**Comment by StephenHinck** [comment]
Hi @Khatcode , the button is here:

![image](https://github.com/SpecterOps/BloodHound/assets/12970156/c7a9fef5-ea1c-44b1-b855-b792904be927)

Although you're free to reverse-engineer the saved query structure in PostgreSQL, the officially supported mechanism for doing so is via the API.

**Comment by Khatcode** [comment]
Aint no way I missed that. Thank you so much
