### ISSUE TITLE
Have means in GUI to copy DN of selected node to clipboard.

### ISSUE THREAD

**Issue by jaredbarez** [SpecterOps/BloodHound#604]
**Feature Description:**
Full DN string of selected node can be copied from BHCE GUI to clipboard.

*Provide a clear and concise description of the feature you're requesting.*
Provide means in BHCE GUI to copy DN of selected node to clipboard by selecting string of DN and then hitting ctrl+c.

**Current Behavior:**
Currently, if DN string doesn't fit into textbox it gets truncated with dots "..." which prevents copying of full DN string.

*Explain how the software behaves currently in relation to the feature you're requesting.*
Currently, if DN string doesn't fit into textbox it gets truncated with dots "...".

**Desired Behavior:**
Instead of truncating DN string in textbox with dots "..." introduce horizontal scroll bar within textbox in order to have possibility to copy full DN string to clipboard. Other option would be to have multiline textbox regarding displaying DN which would word-wrap DN string instead of truncating it with dots "...".

*Describe how you envision the software behaving after the proposed feature is implemented.*
It would let user copy DN string of selected node from the textbox to clipboard.

**Use Case:**
In many many many situations I have to copy DN of the selected node and paste it into some other tool.

*Explain the context in which this feature would be useful. How will it benefit users or contributors?*
It will benefit them largely because DN's of objects are often used throughout analysis.

**Implementation Suggestions:**
Either using horizontal scroll bar or using multiline wordwrapped DN string.

*Optional: If you have any suggestions on how this feature could be implemented, you can provide them here.*
n/a

**Additional Information:**

*Include any other relevant information that could help in understanding or implementing the feature.*
![Screenshot from 2024-05-10 16-19-16](https://github.com/SpecterOps/BloodHound/assets/13761356/1272ebe1-4eb3-41ea-b62f-3bfdb30efbbe)

**Comment by martinsohn** [comment]
Hi @jaredbarez , here are two workarounds will select the entire string:

1. Triple-click the string
2. Click and hold to the left of the string, then drag your cursor below the string

Demo:

![msedge_K2rkfdWJ9L](https://github.com/user-attachments/assets/706b796d-82e8-4387-8977-e9ac2c41de67)

**Comment by jaredbarez** [comment]
Thanks @martinsohn
