### ISSUE TITLE
New Pre-built Cypher queries & Modification suggest

### ISSUE THREAD

**Issue by H3lli0t** [SpecterOps/BloodHound#606]
## Description 1

I suggest adding two new pre-built Cypher queries : 

- Paths from non admin users to computers with GoldenCert edge.
- Paths from non admin users to principals who can retrieve the GMSA password.

#### Query 1

```
MATCH (c:Computer)-[:HostsCAService]->(:EnterpriseCA) WITH COLLECT(c.name) AS GoldenCertComputer
MATCH p=(:User {admincount:false})-[]->(c1:Computer) WHERE c1.name IN GoldenCertComputer
RETURN p
```
![Q1](https://github.com/SpecterOps/BloodHound/assets/98268236/1bb4b3c6-168d-4d12-8ef8-2e1e57bd4444)

#### Query 2

```
MATCH (a)-[:ReadGMSAPassword]->(b:User)
WITH COLLECT(a.name) AS CanReadGMSAPassword
MATCH p=(u:User {admincount:false})-[]->(b)
WHERE b.name IN CanReadGMSAPassword
RETURN p
```
![Q2](https://github.com/SpecterOps/BloodHound/assets/98268236/5b2dae9c-6c9b-4221-9c10-9220da5ab9b1)

## Description 2

I also suggest modifying the query of "Dangerous Privileges for Domain Users group" to : 

```
MATCH p=(u:User {admincount:false})-[r:Owns|WriteDacl|GenericAll|WriteOwner|ExecuteDCOM|GenericWrite|AllowedToDelegate|ForceChangePassword|AdminTo|AllExtendedRights]->(n)
MATCH (u:User {admincount:false})-[:MemberOf*1..]->(m)
WHERE m.objectid ENDS WITH "-513"
RETURN p
```
![Q3](https://github.com/SpecterOps/BloodHound/assets/98268236/f14d95be-434f-4202-a639-b8c60eb000a7)

**Comment by StephenHinck** [comment]
The queries provided in the interface are designed to be a sample of what is possible with the Cypher query language, not an all-encompassing list of possible scenarios that introduce risk to an environment. While we recognize that these queries may interest some users, we've decided not to include them in the product at this time.
