### ISSUE TITLE
Support multiple end nodes

### ISSUE THREAD

**Issue by CaledoniaProject** [SpecterOps/BloodHound#634]
The Path Search function only allow single end nodes, how can I input multiple one without writing custom queries?

**Comment by elikmiller** [comment]
Hey @CaledoniaProject - this feature is not supported. If you'd like you can request this feature using the Feature Request template at https://github.com/SpecterOps/BloodHound/issues/new/choose

More than likely though we won't implement such a feature and you should instead use a custom cypher query.
