### ISSUE TITLE
Cant login new instance, bloodhound-1 exited with code 137

### ISSUE THREAD

**Issue by TheKevinWang** [SpecterOps/BloodHound#640]
**Description:**

cant login new instance. bloodhound crashes. 

bloodhound-1 exited with code 137

**Component(s) Affected:**

- [ ] UI
- [ ] API
- [ ] Neo4j
- [ ] PostgreSQL
- [ ] Data Collector (SharpHound, AzureHound)
- [ ] Other (tooling, documentation, etc.)

**Steps to Reproduce:**

setup new instance, `docker compose up` then using password supplied and `admin` as username it fails and then I get error blooodhound exit

**Expected Behavior:**

*A description of what you expected to happen.*

**Actual Behavior:**

*A description of what actually happened.*

**Screenshots/Code Snippets/Sample Files:**

*If applicable, add screenshots, relevant code snippets, or sample files that help illustrate the issue.*

**Environment Information:**

BloodHound: [BloodHound version or revision]

Collector: [SharpHound version / AzureHound version]

OS: [your OS and version]

Browser (if UI related): [browser name and version]

Node.js (if UI related: [Node.js version]

Go (if API related): [Go version]

Database (if persistence related): [Neo4j version / PostgreSQL version]

Docker (if using Docker): [docker version]

**Additional Information:**

*Any additional context or information that might be helpful in understanding and diagnosing the issue.*

**Potential Solution (Optional):**

*If you have any ideas about what might be causing the issue or how it could be fixed, you can share them here.*

**Related Issues:**

*If you've found related issues in the project's issue tracker, mention them here.*

**Contributor Checklist:**

- [ ] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [ ] I have provided clear steps to reproduce the issue.
- [ ] I have included relevant environment information details.
- [ ] I have attached necessary supporting documents.
- [ ] I have checked that any JSON files I am attempting to upload to BloodHound are valid.

**Comment by TheKevinWang** [comment]
just have to use debug for now I guess

**Comment by MattGrol** [comment]
Hi, I have the same problem... How to fix it? Thanks

**Comment by StephenHinck** [comment]
Docker exit code 137 means insufficient memory was supplied for the container to function. If you'd like to provide additional information such as fuller logs or system details we can take a look, but generally it means more resources (memory) are required.
