### ISSUE TITLE
Upload of larger json files crashes the application due to too much memory consumption

### ISSUE THREAD

**Issue by JonasBK** [SpecterOps/BloodHound#66]
**Description:**

The application will in some cases crash when uploading larger json files.
It returns a 137 exit code, indicating the process is terminated because it's using too much memory.

The issue seems unrelated to the 1 GB upload limit, as it happens with files that are less than 1 GB.

The issue has been experienced by at least three community members: https://bloodhoundhq.slack.com/archives/C20NG2L87/p1693296837190309

According to the community member reporting the bug, the VM running docker has 8 GB RAM, so it is not the VM that needs more RAM.

**Component(s) Affected:**

- [X] UI
- [X] API
- [ ] Neo4j
- [ ] PostgreSQL
- [ ] Data Collector (SharpHound, AzureHound)
- [X] Other (tooling, documentation, etc.)

**Steps to Reproduce:**

See slack thread: https://bloodhoundhq.slack.com/archives/C20NG2L87/p1693296837190309
I have not reproduced the issue as I do not have a large json file to test with. I will update the issue when I have reproduced it.

**Expected Behavior:**

Ideally, the application should not attempt to load the file to memory if the file is too big and the UI should display a warning incl. a link to documentation on how to increase this memory limit. If possible, the memory limit should be set to a reasonable size during installation (e.g. 2 GB) and documentation should show how this limit can be modified before and after installation.

It seems like the memory limit can be specified in both the docker-compose file and in Docker Desktop:
- Docker compose file: https://stackoverflow.com/a/42345411
- Docker Desktop: https://stackoverflow.com/a/67900629
I have not tested the above solutions.

**Actual Behavior:**

Application crashes with exit code 137.

**Screenshots/Code Snippets/Sample Files:**

![image](https://github.com/SpecterOps/BloodHound/assets/12843299/e7666629-2e67-4adf-812f-131690f0b7eb)

**Environment Information:**

BloodHound: BHCE latest (5.0)

OS: Linux (issue might also exist on other OS)

Browser (if UI related): Firefox

Docker (if using Docker): Unknown

**Additional Information:**

No additional info.

**Potential Solution (Optional):**

See Expected behavior.

**Related Issues:**

No related issues.

**Contributor Checklist:**

- [X] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [ ] I have provided clear steps to reproduce the issue.
- [ ] I have included relevant environment information details.
- [X] I have attached necessary supporting documents.
- [ ] I have checked that any JSON files I am attempting to upload to BloodHound are valid.

**Comment by elikmiller** [comment]
This error message is coming from docker, not BloodHound. We should be able to take a look at the output of `docker stats` while BloodHound is handling a file upload to see which container is running out of memory. I don't believe there is anything for us to fix here besides maybe having a better understanding of the application's memory usage and documenting some appropriate minimum system requirements.

**Comment by StephenHinck** [comment]
Closing this issue out for now as this relates to memory allocation with Docker. If additional info is available to point towards a problem with the BHCE code, please feel free to re-open.
