### ISSUE TITLE
Feature Request: Include Collector version/source in JSON files

### ISSUE THREAD

**Issue by mubix** [SpecterOps/BloodHound#69]
It's would be nice to have the collector version and source in all of the JSON files. If the person performing the collection isn't the same person doing the ingesting it can sometimes cause problems in debugging issues.

**Comment by elikmiller** [comment]
**Feature Description:**

Include collector version information when generating JSON output

**Current Behavior:**

JSON outputted from SharpHound or AzureHound do not provide any clear indication on which version of either collector was used to generate the data.

**Desired Behavior:**

It is clear what version of collector was used to generate a given JSON file.

**Use Case:**

If the person performing the collection isn't the same person doing the ingesting it can sometimes cause problems in debugging issues.

**Implementation Suggestions:**

Include something like 

```
{"collector": "SharpHound", version: "2.0.0"}
```
at the top of each JSON file produced by SharpHound or AzureHound.

**Additional Information:**

None

**Comment by mubix** [comment]
@elikmiller that's perfect. I might even go so far as to include the flags that were used during execution sort of like Nmap does in it's files.

**Comment by StephenHinck** [comment]
Hey there - this was included in https://github.com/BloodHoundAD/SharpHoundCommon/pull/139
