### ISSUE TITLE
Feature Request: Database management and support for multiple projects

### ISSUE THREAD

**Issue by fsacer** [SpecterOps/BloodHound#72]
**Feature Description:**

Since BloodHound CE supports multiple users, one would expect support for multiple projects as well. It would be useful to have a button to clear the database like there was before with the original BloodHound as well.

**Current Behavior:**

Currently, Bloodhound CE imports all data into a single Neo4J database.

**Desired Behavior:**

BloodHound CE would manage multiple collections of ingestion imports separately or together.

**Use Case:**

It would be useful to have one BloodHound instance available for multiple testers and teams with separate projects.

**Implementation Suggestions:**

This probably means BloodHound would manage the connections for multiple Neo4J databases that would separately hold data for multiple projects/clients.  

**Additional Information:**

/

**Comment by mohamedeletrepy** [comment]
how can i remove the old database i upload , after some searching i found this 
![Screenshot from 2023-09-02 15-45-40](https://github.com/SpecterOps/BloodHound/assets/91216468/8f93ef19-26c4-45c2-bae5-e03a8ee7011f) but i don't where is my uploaded .json file in this

**Comment by StephenHinck** [comment]
We would suggest deploying multiple compose stacks utilizing the existing toolsets and examples, which will also let you segment access to the data for each project.
