### ISSUE TITLE
can't deleted old .json file 

### ISSUE THREAD

**Issue by mohamedeletrepy** [SpecterOps/BloodHound#73]
I can't delete old .json file tell me how to delete the database in that plz make a button like an old bloodhound to clear the database

**Comment by StephenHinck** [comment]
Hi there, we don't currently have an in-product button for this, however, you can clear out the Neo4J database using the following:

- For Bash compatible shells: `docker volume rm $(docker volume ls -q | grep neo4j-data)`
- For PowerShell: `docker volume rm @(docker volume ls -q | Select-String neo4j-data)`

I'll modify the request to use this as a feature request to add the functionality into the product.
