### ISSUE TITLE
User role doesn't have Graph Write access so can't upload files

### ISSUE THREAD

**Issue by camelx0** [SpecterOps/BloodHound#74]
**Description:**

The User role appears to not have sufficient permission to upload files and write to the graph db. The Upload-only role has the GraphDBWrite permission but the User role only has the GraphDBRead permission. This is also contrary to the documentation under User Role Definitions. 

**Component(s) Affected:**

- [X] UI
- [ ] API
- [X] Neo4j
- [ ] PostgreSQL
- [ ] Data Collector (SharpHound, AzureHound)
- [ ] Other (tooling, documentation, etc.)

**Steps to Reproduce:**

1. Go to Manual File Ingest as a user with the User role
2. Click on Upload Files
3. Add files to upload and select Upload
4. See error at bottom left: "Permission Denied!"

**Expected Behavior:**

The User role should be able to successfully upload files manually, similar to the Upload-only role.

**Actual Behavior:**

The User role is unable to upload files manually.

**Screenshots/Code Snippets/Sample Files:**

Code: https://github.com/SpecterOps/BloodHound/blob/main/cmd/api/src/auth/role.go

**Environment Information:**

BloodHound: BloodHound CE latest

Collector: Sharphound 2.0

OS: MacOS Ventura 13.5.1

Docker: 24.0.5

**Potential Solution:**

For the User role, change the permissions.GraphDBRead to permissions.GraphDBWrite

<img width="1153" alt="Permission Denied" src="https://github.com/SpecterOps/BloodHound/assets/43326070/bec19551-ea02-4ce4-baac-abe90a385d87">

**Comment by StephenHinck** [comment]
Hi there - this is by design so that users cannot modify the graph, only Administrators.
