### ISSUE TITLE
API Endpoint graphs/cypher does not work as described

### ISSUE THREAD

**Issue by Daniel-CS-Team** [SpecterOps/BloodHound#79]
**Description:**

The buil-in API documentation for the endpoint `graphs/cypher` reads as follows:
> Runs a manual cypher query directly against the database

Which made me expect, that whatever Cypher-Query is send to that endpoint is directly passed to neo4j. That is clearly not the case, as not all queries that work in neo4j-browser do work with this endpoint as well. The behavior can be reproduced in the GUI as well, since it uses the same Endpoint.

**Component(s) Affected:**

- [X] UI
- [X] API
- [X] Neo4j
- [ ] PostgreSQL
- [ ] Data Collector (SharpHound, AzureHound)
- [X] Other (tooling, documentation, etc.)

**Steps to Reproduce:**

1. In the Bloodhound GUI, go to Explore -> Cypher
2. Copy and paste this query: `WITH datetime() as now MATCH (n) WHERE duration.between(datetime(n.lastseen),now).hours > 1 RETURN n LIMIT 10'`

**Expected Behavior:**

Should return 10 Nodes.

**Actual Behavior:**

Gives Error `invalid input`

**Screenshots/Code Snippets/Sample Files:**
-

**Environment Information:**

BloodhoundCE in AWS ECS

Neo4j Browser version: [5.11.0](https://github.com/neo4j/neo4j-browser/releases/tag/5.11.0)

Neo4j Server version: [4.4.25](https://github.com/neo4j/neo4j/wiki/Neo4j-4.4-changelog#4425) (community)

**Additional Information:**

If the same query is run in neo4j-browser against the very same database, it works just fine.

**Potential Solution (Optional):**

Either correct the documentation to describe the actual behavior or really just forward the query directly to neo4j.

**Related Issues:**
-

**Contributor Checklist:**

- [X] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [X] I have provided clear steps to reproduce the issue.
- [X] I have included relevant environment information details.
- [X] I have attached necessary supporting documents.
- [ ] I have checked that any JSON files I am attempting to upload to BloodHound are valid.

**Comment by StephenHinck** [comment]
We can update the documentation to reflect how this functions more accurately. There is a setting at https://github.com/SpecterOps/BloodHound/blob/main/examples/docker-compose/docker-compose.yml#L66C13-L66C13 that enables or disables some of the filtering. However, we're tracking a bug internally where that setting only disables the timing constraints while leaving the expression constraints intact. We'll use this ticket to track both issues.

**Comment by spyr0-sec** [comment]
@StephenHinck apologies for the bump but I was wondering if there has been any update on this? Would be ideal to add some paths between on-prem and Azure nodes which hopefully this would allow me to do.

**Comment by StephenHinck** [comment]
We haven't had an opportunity to work on this, no. Your workaround will work just fine - BHCE queries data out of Neo; nothing special there.

**Comment by spyr0-sec** [comment]
It looks like there's just been a PR to fix this https://github.com/SpecterOps/BloodHound/pull/190 thank you very much! @superlinkx

**Comment by StephenHinck** [comment]
Unfortunately, that PR does not fix this issue. The disable qc flag currently only disables the heuristic timeouts on cypher queries.

**Comment by superlinkx** [comment]
It should be noted this PR only fixes the env var not being parsed properly. To give context, this current incarnation of `disable_cypher_qc` only disables query complexity QoS levers (that is, figuring out if a query is going to be too costly to attempt to run before we run it). 

There are several community expectations that it also allows for more standard Cypher queries to work (such as CREATE queries). For now, we don't have a way wired up to disable these guardrails, but we are discussing internally how to solve multiple community issues surrounding our cypher QoS settings and expanded cypher language support. We'll be sure to communicate plans as soon as we are able.

**Comment by spyr0-sec** [comment]
Understood, thanks both for all your hard work on this!

**Comment by StephenHinck** [comment]
This should be resolved with v5.8.0
