### ISSUE TITLE
Bug: Initial Password use gives failed login consistently

### ISSUE THREAD

**Issue by neet-h-patel** [SpecterOps/BloodHound#838]
## Description:

Following the install instructions for Bloodhound CE exactly as described for Linux, results in failed
login for initial password provided.

### Are you intending to fix this bug?

No.

## Component(s) Affected:

- UI

## Steps to Reproduce:

1. Follow the linux install from https://support.bloodhoundenterprise.io/hc/en-us/articles/17468450058267-Install-BloodHound-Community-Edition-with-Docker-Compose

2. Copy paste the initial password
<img width="638" alt="Screenshot 2024-09-04 at 6 48 45 PM" src="https://github.com/user-attachments/assets/7cc7423c-b65c-4793-9e71-25759fca892d">

3. Enter the password in the UI
<img width="531" alt="Screenshot 2024-09-04 at 6 49 19 PM" src="https://github.com/user-attachments/assets/f0f491ab-fcd2-492e-81b1-bf4b87f9fc1f">

5. See error at this point

## Expected Behavior:

Successful login

## Actual Behavior:

Failed login

## Screenshots/Code Snippets/Sample Files:

*If applicable, add screenshots, relevant code snippets, or sample files that help illustrate the issue.*

## Environment Information:

BloodHound: v5.14.0

Collector: [SharpHound version / AzureHound version]

OS: kali 2024.2

Browser (if UI related): [browser name and version]

Node.js (if UI related: [Node.js version]

Go (if API related): [Go version]

Database (if persistence related): [Neo4j version / PostgreSQL version]

Docker (if using Docker): [docker version]

## Additional Information:

*Any additional context or information that might be helpful in understanding and diagnosing the issue.*

## Potential Solution (optional):

*If you have any ideas about what might be causing the issue or how it could be fixed, you can share them here.*

## Related Issues:

*If you've found related issues in the project's issue tracker, mention them here.*

## Contributor Checklist:

- [ ] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [ ] I have provided clear steps to reproduce the issue.
- [ ] I have included relevant environment information details.
- [ ] I have attached necessary supporting documents.
- [ ] I have checked that any JSON files I am attempting to upload to BloodHound are valid.

**Comment by cidrmill** [comment]
I'm also experiencing this. BH crashes every time I try logging in also.

**Comment by StephenHinck** [comment]
Can you please provide the logs from the API from when you attempted to log in? Those may give us additional clues about where/how to help with this issue.

**Comment by neet-h-patel** [comment]
Hello. How do I collect those? I'm running it through docker-compose. Also, in running it again, I was able login again so perhaps the issue is resolved? But I can still provide you the logs for inspection just in case. I just don't know how.

**Comment by StephenHinck** [comment]
If you ran your environment with `docker-compose up`, you'll see those logs in your terminal window.

You should also be able to run `docker compose logs` (add a `-f` in there to follow) to see the logs from the environment as you're running.

**Comment by neet-h-patel** [comment]
Attaching logs from re-running initial install of BH CE. It had worked this time like I had mentioned but to inspect nevertheless...
[initial_startup.log](https://github.com/user-attachments/files/16968014/initial_startup.log)

**Comment by neet-h-patel** [comment]
UPDATE: when I run docker-compose pull && docker-compose up after running docker-compose down -v,
I'm able to get to the password rest page but then it fails and says an error encountered
[password_reset.log](https://github.com/user-attachments/files/16985453/password_reset.log)
![Uploading Screenshot 2024-09-12 at 2.06.56 PM.png…]()

**Comment by StephenHinck** [comment]
Thank you so much for including the API logs - that's exactly what I needed.

The "Exited with code 137" on the last line indicates you've not provisioned enough memory for your containers. The OOM condition is almost certainly coming from our Argon2 code, which is our preferred PBKDF. Derivation functions usually require multiple iterations and a large memory scratch space to function, hence the crash here.

The key derivation step will use 1GB of memory on its own. For even a small environment, I recommend deploying with at least 4GB of memory allocated to your containers—this will also be utilized after you ingest data for performing queries, etc.

**Comment by Austiemo** [comment]
Thank you so much for this. I spent 3 hours troubleshooting the same issue.  I changed VM ram to 6GB from 2GB the password reset page worked on the first try.

**Comment by Byxs20** [comment]
这个是我的方法：

```python
# 首先要到 bloodhound-cli 目录中删除容器
docker-compose down -v

# 再使用 docker-compose 创建容器
docker-compose up -d
```

这个时候密码其实就在 `bloodhound.config.json` 中，你可以看到密码是多少，然后再登录
