### ISSUE TITLE
Feature: Modify OpenAPI spec to workaround limitations of code generators

### ISSUE THREAD

**Issue by daviditkin** [SpecterOps/BloodHound#847]
## Feature Description
Modify the BloodHound OpenAPI spec to workaround limitations of code generators.

The OpenAPI spec causes the oapi-codegen generator to fail or create invalid go client code for the following constructs:
- Some response schemas that are defined in place and contain combinations of anyOf,  allOf  cause the generation of incorrect code.
- There are properties defined, mostly deprecated properties, that cause duplicate struct field names to be generated.

### Are you intending to implement this feature?
yes

## Current Behavior

The bloodhound OpenAPI spec causes some code generators to produce invalid go client code.

## Desired Behavior

Modify the OpenAPI spec to workaround generator limitations and allow valid go client code to be generated.

## Use Case

Using an openapi code generator to generate client code.

## Implementation Suggestions

- Use indirection through a $ref to a newly created response type to workaround code generator issues.
- Add x-go-name extension tags to prevent duplicate field names from being generated.

**Comment by sircodemane** [comment]
Hi @daviditkin, we have reviewed this and it's good to go as described! Feel free to create the PR when ready

**Comment by daviditkin** [comment]
Hey @sircodemane, The modifications required mainly deal with the response definitions of some endpoints.

I want to confirm that it is necessary for bloodhound response json remain the same after my modifications.  
What should be done if the response can not be made identical after refactoring?
