### ISSUE TITLE
I forget password for login

### ISSUE THREAD

**Issue by mohamedeletrepy** [SpecterOps/BloodHound#85]
i forget the password of login how can i reset it

**Comment by StephenHinck** [comment]
Hi there, the password hashes are stored in Postgres. You'll need to find the ID of the user you want to reset the password for and then set a new hash in the `auth_secrets` table using an Argon2 hash. The following example would find and then set a user's password to `admin`:

```
postgres=> select id from users where principal_name='admin';
 
id
--------------------------------------
long-uuid-value
 
postgres=> update auth_secrets set digest='$argon2id$v=19$m=1048576,t=1,p=2$QUB3+B/dvvpbOYKT9Wr1EA==$3sV71u+fW4kX+euamzIgOQ==' where user_id='long-uuid-value';
```

**Comment by mohamedeletrepy** [comment]
Thank bro and i want to remove old data on it how can i remove old database which i upload it

**Comment by mohamedeletrepy** [comment]
can u tell me how to access my postgres ?

**Comment by StephenHinck** [comment]
From the sound of it, you're looking for a fresh start anyway?

If so, I would suggest running `docker compose down -v`. This will tear down the entire deployment and remove all the data. Afterward, you can run `docker compose up -d`, which will recreate your environment, let you reset your default password, and have a blank Neo4J database ready to be populated with new data.
