### ISSUE TITLE
Bug: Color of text in textfields in API Explorer is the same as the background

### ISSUE THREAD

**Issue by rtpt-romankarwacik** [SpecterOps/BloodHound#850]
## Description:

The color of text in textfields in the API explorer is the same as the background color

### Are you intending to fix this bug?

No

## Component(s) Affected:

- UI

## Steps to Reproduce:

1. Activate Dark Mode
2. Go to API Explorer
3. Expand any Endpoint
4. Click "Try it out"
5. Enter anything in a textfield
6. Text is not visible due to color

## Expected Behavior:

Input text should be visible.

## Actual Behavior:

Input text is not visible

## Screenshots/Code Snippets/Sample Files:

See "Test" written in the "Prefer" textfield in light mode, but not in dark mode.

![api_explorer_dark_mode](https://github.com/user-attachments/assets/89752d8d-5e15-43d1-92fa-7851e04133aa)
![api_explorer_light_mode](https://github.com/user-attachments/assets/1071e842-b7b1-4e39-8658-21d6e2a92416)

## Environment Information:

BloodHound: v5.15.0

Browser (if UI related): Firefox 129.0.2

Node.js (if UI related: 18.19.0

## Contributor Checklist:

- [x] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [x] I have provided clear steps to reproduce the issue.
- [x] I have included relevant environment information details.
- [x] I have attached necessary supporting documents.

**Comment by slokie-so** [comment]
Corrected as of v6.0
