### ISSUE TITLE
Bug: Healthcheck in example docker compose uses wrong port

### ISSUE THREAD

**Issue by yannis-srl** [SpecterOps/BloodHound#862]
## Description:

When downloading the example docker compose from the link in the README and then changing the NEO4J_WEB_PORT environment variable the healthcheck breaks and the bloodhound ui will not start. This is because the env variable NEO4J_WEB_PORT is used in the healthcheck command, even tough it only affects the port exposed on the host not the port exposed inside the container.

### Are you intending to fix this bug?

Yes.

## Component(s) Affected:

- Other (tooling, documentation, etc.)

## Steps to Reproduce:

1. Download https://github.com/SpecterOps/BloodHound/blob/main/examples/docker-compose/docker-compose.yml as specified in README.
2. Set env variable NEO4J_WEB_PORT to any port, e.g. 16666
3. Run `docker compose pull && docker compose up`

## Expected Behavior:

All three containers start and the neo4j web interface is reachable via the specified port.

## Actual Behavior:

The healthcheck fails, even tough the neo4j web interface is reachable and the bloodhound ui container never starts.

## Environment Information:

BloodHound: v5.15

Collector: None

OS: MAC OS 14.6

Docker: 27.0.3

## Additional Information:

As far as I can tell this is already fixed in the docker-compose.dev.yml and should just be a problem of an outdated example file.

## Potential Solution (optional):

Hardcode the port of the healthcheck to 7474 (same for postgres with port 5432) because the internal port is also hardcoded.

## Contributor Checklist:

- [X] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [X] I have provided clear steps to reproduce the issue.
- [X] I have included relevant environment information details.

**Comment by yannis-srl** [comment]
#864 should solve this issue.

**Comment by StephenHinck** [comment]
This was closed with #864
