### ISSUE TITLE
Error: cannot unmarshal number into Go struct field Trust.Trusts.TrustDirection of type string

### ISSUE THREAD

**Issue by Daniel-CS-Team** [SpecterOps/BloodHound#87]
**Description:**

While ingesting, the following error is loged:
`Error processing ingest task: json: cannot unmarshal number into Go struct field Trust.Trusts.TrustDirection of type string`

**Component(s) Affected:**

- [ ] UI
- [ ] API
- [ ] Neo4j
- [ ] PostgreSQL
- [ ] Data Collector (SharpHound, AzureHound)
- [X] Other (tooling, documentation, etc.)

**Steps to Reproduce:**

1. Transcode Sharphound Output as described in [Issue 30](https://github.com/SpecterOps/BloodHound/issues/30) (not sure if related...)
2. Upload Sharphound Output
3. Observe logs

**Expected Behavior:**

Ingestion should work without errors

**Actual Behavior:**

Above mentioned error is loged. Furthermore, domain trust are not processed correctly and are not visible in the GUI

**Screenshots/Code Snippets/Sample Files:**

-

**Environment Information:**

BloodHound: latest Docker-Image

Collector: SharpHound 2.0.0

Docker (if using Docker): AWS ECS FARGATE

**Additional Information:**

- 

**Potential Solution (Optional):**

- 

**Related Issues:**

- 

**Contributor Checklist:**

- [X] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [X] I have provided clear steps to reproduce the issue.
- [X] I have included relevant environment information details.
- [X] I have attached necessary supporting documents.
- [X] I have checked that any JSON files I am attempting to upload to BloodHound are valid.

**Comment by rvazarkar** [comment]
v2.0.1 has been release which fixes this issue
