### ISSUE TITLE
Security Bad Practice - Hardcoded Credentials in bloodhound.config.json

### ISSUE THREAD

**Issue by Daniel-CS-Team** [SpecterOps/BloodHound#9]
I consider it a very bad practice to hardcode any kind of credentials into config-files.

Maybe you can add a little entrypoint.sh wrapper, that retrieves credentials from environment variables, so that one can set them at runtime. I am no pro-developer, but something like this should do the job:

```
echo "{\"version\":1,\"bind_addr\":\"0.0.0.0:8080\",\"metrics_port\":\":2112\",\"root_url\":\"http://127.0.0.1:8080/\",\"work_dir\":\"/opt/bloodhound/work\",\"log_level\":\"${LOG_LEVEL:-INFO}\",\"log_path\":\"bloodhound.log\",\"features\":{\"enable_auth\":true},\"tls\":{\"cert_file\":\"\",\"key_file\":\"\"},\"database\":{\"connection\":\"user=${DB_USER:-bloodhound} password=${DB_PASSWORD:-bloodhoundcommunityedition} dbname=${DB_NAME:-bloodhound} host=${DB_HOST:-app-db}\"},\"neo4j\":{\"connection\":\"${NEO_CONNECTION_STRING:-neo4j://neo4j:bloodhoundcommunityedition@graph-db:7687/}\"},\"collectors_base_path\":\"/etc/bloodhound/collectors\"}" > /bloodhound.config.json
exec bloodhound -config /bloodhound.config.json
```

BTW: Thanks for your great work. Hopefully, we can make it even better.

**Comment by Acebond** [comment]
Having creds stored in config files is a correct way to keep/store credentials.

**Comment by Acebond** [comment]
How about instead of just saying "very bad practice" and having a whinge you demonstrate and explain why storing credentials in a config file is bad?

**Comment by Acebond** [comment]
Also your proposed solutions to a problem and doesn't exist has multiple naïve errors. 
If any of a environment variables contain JSON escape characters your bash script breaks imminently and would crash.

**Comment by zinic** [comment]
At minimum, we can provide additional documentation and justification for our practice here even if the risk is indeed low.

The intent of the issue appears genuine and requires an equally genuine response from the BloodHound team, even if we don't take on the author's suggested fixes.

**Comment by zinic** [comment]
Thanks for the additional information. It will help frame our internal discussion about this issue.
