### ISSUE TITLE
Bug: Newly created SAML providers fail with HTTP 500

### ISSUE THREAD

**Issue by 0xd6cb6d73** [SpecterOps/BloodHound#949]
## Description:

Newly created SAML providers seem to be incorrectly created and are unusable.

### Are you intending to fix this bug?

No

## Component(s) Affected:

- API

## Steps to Reproduce:

On BHCE v6.2.0-rc5:
1. Create a new SAML provider using some metadata.xml
2. Try to access the metadata page
3. Try to access the provider's login page
4. call the `/api/v2/saml` endpoint
5. call the `/api/v2/saml/providers/{new_provider_id}` endpoint

## Expected Behavior:

The metadata file should be accessible.
The login page should be accessible (SAML configuration and authentication success notwhistanding).
The SAML provider returned by the `/api/v2/saml/providers/{new_provider_id}` call should match that observed in the `api/v2/saml` call and not have empty URI fields.

## Actual Behavior:

Attempting to access the metadata file or the login page fails instantly with a 500 error. This is before the IdP is called to do anything.

## Screenshots/Code Snippets/Sample Files:

Browsing to the metadata file or the login page results in:
```
{
    "http_status": 500,
    "timestamp": "2024-11-12T17:28:33.010153314Z",
    "request_id": "0793ce1b-5209-4bb2-b424-831ac86bca2b",
    "errors": [
        {
            "context": "",
            "message": "an internal error has occurred that is preventing the service from servicing this request"
        }
    ]
}
```

Result of the `api/v2/saml` call:
```
{
        "name": "<SOME_NAME>",
        "display_name": "<SOME_NAME>",
        "idp_issuer_uri": <MY_IDP_URN>,
        "idp_sso_uri": <MY_IDP_URI>,
        "principal_attribute_mappings": null,
        "sp_issuer_uri": <MY_ISSUER_ID>,
        "sp_sso_uri": <MY_SSO_URI>,
        "sp_metadata_uri": <MY_METADATA_URI>,
        "sp_acs_uri": <MY_ACS_URI>,
        "sso_provider_id": 3,
        "id": 3,
        "created_at": "2024-11-12T16:50:11.622619Z",
        "updated_at": "2024-11-12T16:50:11.622619Z",
        "deleted_at": {
          "Time": "0001-01-01T00:00:00Z",
          "Valid": false
        }
}
```

Result of the `/api/v2/saml/providers/3` call:
```
"data": {
    "name": <SOME_NAME>,
    "display_name": <SOME_NAME>,
    "idp_issuer_uri": <MY_IDP_URN>,
    "idp_sso_uri": <MY_IDP_URI>,
    "principal_attribute_mappings": null,
    "sp_issuer_uri": "",
    "sp_sso_uri": "",
    "sp_metadata_uri": "",
    "sp_acs_uri": "",
    "sso_provider_id": 3,
    "id": 3,
    "created_at": "2024-11-12T16:50:11.622619Z",
    "updated_at": "2024-11-12T16:50:11.622619Z",
    "deleted_at": {
      "Time": "0001-01-01T00:00:00Z",
      "Valid": false
    }
  }
```
## Environment Information:

BloodHound: v6.2.0-rc5

OS: RHEL9

Go : go1.23

Database: PSQL 16

## Additional Information:

This also happened on v6.2.0-rc2. I upgraded to rc5 to see if there was a fix. These are both a new (PSQL-wise) BHCE instance. 

My other instance on v6.2.0-rc2 does not have this issue both with SAML providers created prior (v5.X and v6.0.0) and new ones. This older instance has been migrated from PSQL13 to PSQL16.

## Contributor Checklist:

- [x ] I have searched the issue tracker to ensure this bug hasn't been reported before or is not already being addressed.
- [ x] I have provided clear steps to reproduce the issue.
- [ x] I have included relevant environment information details.
- [x ] I have attached necessary supporting documents.

**Comment by mistahj67** [comment]
Thanks for the bug report, unfortunately we haven't been able to reproduce the crux of this issue yet. 

That said, the `/api/v2/saml/providers/{new_provider_id}` endpoint **does** indeed fail to provide the uri's and is an existing formatting bug, thanks for pointing that out. Its `v1` variant correctly formats those. We'll be sure to note and fix this in the coming releases.

Can you please elaborate on how you created the new SAML provider, was it through the API (if so, which endpoint) or through the admin management page?

If you can also provide the metadata and login endpoints you are referring to, that might help narrow this down (feel free to redact ids / slugs).

Finally, there have been a number of migration changes as we've worked in this area recently and it's entirely possible if you routinely run builds off the tip of the spear / main that your database schema is outdated or missing a vital change. If you have access to the postgres db directly, you can remove the last few migration records, `v6.1.0` and `v6.2.0` and restart your instance to see if that resolves the issue. Alternatively, **and more destructively,** you can remove your  postgres volume entirely and start from scratch.

**Comment by 0xd6cb6d73** [comment]
The SAML provider was created as an administrator user through the UI. The IdP's `metadata.xml` was uploaded without issue. I also tried the `/api/v2/saml/providers` call through the explorer but got a 400 - too large error. I didn't spend a lot of time on this so I'll be happy to retry if there's another way. I'm afraid I'm not at all familiar with the API bits that aren't in the explorer.

Here are the metadata and login endpoints I spoke of:
```
<MY_BHCE_HOSTNAME>/api/v2/sso/<MY_SAML_PROVIDER_NAME>/login
<MY_BHCE_HOSTNAME>/api/v2/login/saml/<MY_SAML_PROVIDER_NAME>/metadata
```

I am building from the stage/`version`  branches. The instance on which I observed this issue is clean, that is to say that the PSQL database was created on v6.2.0. Anecdotally, I saw the log messages relating to all the SQL migrations although I didn't pay that much attention so it's possible that one was missing.

**Comment by 0xd6cb6d73** [comment]
I went back to an older version and noticed the "unable to decode cert" error. Therefore it looks like this is a #83 duplicate. However, it looks like this error isn't logged anymore.

**Comment by mistahj67** [comment]
Can't thank you enough @0xd6cb6d73 for your patience and deep dive to discover the unintended masking of that parsing cert error. 🙇 

The upcoming v6.2.0-rc6 / v6.2.0 official release should properly surface that error, and we were able to squeeze in the formatting URI fix for the `/api/v2/saml/providers/{new_provider_id}` endpoint as well 🎉
